import { isSupabaseConfigured, supabase } from '../../lib/supabaseClient';
import { assertProfitabilityFilters, assertProfitabilitySort, parseProfitabilityBounds, parseProfitabilityExpenses, parseProfitabilityFilterOptions, parseProfitabilityRows, parseProfitabilitySeries, parseProfitabilitySummary, type ProfitabilityBounds, type ProfitabilityExpense, type ProfitabilityFilterOptions, type ProfitabilityFilters, type ProfitabilityRow, type ProfitabilitySeriesRow, type ProfitabilitySort, type ProfitabilitySummary } from './profitabilityDataCore';

const isV5Environment = import.meta.env.VITE_APP_ENV === 'v5-development';
export const isV5ProfitabilityBackendEnabled = isV5Environment && import.meta.env.VITE_V5_PROFITABILITY_BACKEND_ENABLED === 'true';
function assertEnabled() { if (!isV5ProfitabilityBackendEnabled) throw new Error('Серверное чтение «Рентабельности» не включено'); if (!isSupabaseConfigured) throw new Error('Supabase V5 не настроен'); }
async function rpc(name: string, parameters: Record<string, unknown> = {}) { assertEnabled(); const { data, error } = await supabase.rpc(name, parameters); if (error) throw new Error(`Не удалось загрузить V5 «Рентабельность»: ${error.message}`); return data; }
function params(filters: ProfitabilityFilters) { const value = assertProfitabilityFilters(filters); return { p_start: value.start, p_end: value.end, p_cabinet_ids: value.cabinetIds?.length ? value.cabinetIds : null, p_product_ids: value.productIds?.length ? value.productIds : null, p_category_ids: value.categoryIds?.length ? value.categoryIds : null, p_brand_ids: value.brandIds?.length ? value.brandIds : null, p_group_ids: value.groupIds?.length ? value.groupIds : null, p_search: value.search?.trim() || null }; }
export async function loadProfitabilityBounds(): Promise<ProfitabilityBounds> { return parseProfitabilityBounds(await rpc('v5_profitability_bounds')); }
export async function loadProfitabilityFilterOptions(filters: Pick<ProfitabilityFilters, 'start' | 'end'>, limit = 500): Promise<ProfitabilityFilterOptions> { if (!Number.isInteger(limit) || limit < 1 || limit > 500) throw new Error('Лимит фильтров должен быть от 1 до 500'); return parseProfitabilityFilterOptions(await rpc('v5_profitability_filter_options', { p_start: filters.start, p_end: filters.end, p_limit: limit })); }
export async function loadProfitabilitySummary(filters: ProfitabilityFilters): Promise<ProfitabilitySummary> { return parseProfitabilitySummary(await rpc('v5_profitability_summary', params(filters))); }
export async function loadProfitabilitySeries(filters: ProfitabilityFilters): Promise<ProfitabilitySeriesRow[]> { return parseProfitabilitySeries(await rpc('v5_profitability_series', params(filters))); }
export async function loadProfitabilityRows(filters: ProfitabilityFilters, sort: ProfitabilitySort, offset = 0, limit = 100): Promise<ProfitabilityRow[]> { if (!Number.isInteger(offset) || offset < 0 || offset > 100000) throw new Error('Некорректное смещение'); if (!Number.isInteger(limit) || limit < 1 || limit > 1000) throw new Error('Лимит строк должен быть от 1 до 1000'); return parseProfitabilityRows(await rpc('v5_profitability_rows', { ...params(filters), p_sort: assertProfitabilitySort(sort), p_offset: offset, p_limit: limit })); }
export async function loadProfitabilityExpenses(start: string, end: string): Promise<ProfitabilityExpense[]> { return parseProfitabilityExpenses(await rpc('v5_profitability_expenses', { p_start: start, p_end: end })); }
export async function setProfitabilityExpense(cabinetId: string, month: string, expensePct: number): Promise<void> { if (!/^\d{4}-\d{2}-01$/u.test(month) || !Number.isFinite(expensePct) || expensePct < 0 || expensePct > 100) throw new Error('Некорректные параметры постоянных расходов'); await rpc('v5_profitability_set_expense', { p_cabinet_id: cabinetId, p_month: month, p_expense_pct: expensePct }); }
