export interface ProfitabilityFilters { start: string; end: string; cabinetIds?: string[] | null; productIds?: string[] | null; categoryIds?: string[] | null; brandIds?: string[] | null; groupIds?: string[] | null; search?: string | null }
export interface ProfitabilityDimension { id: string; name: string }
export interface ProfitabilityBounds { minDate: string | null; maxDate: string | null }
export interface ProfitabilityFilterOptions { cabinets: ProfitabilityDimension[]; categories: ProfitabilityDimension[]; brands: ProfitabilityDimension[]; groups: ProfitabilityDimension[] }
export interface ProfitabilitySummary { quantity: number; revenue: number; directCosts: number; grossProfit: number; grossMargin: number | null; expenseAmount: number | null; netProfit: number | null; profitability: number | null; productCount: number; expensesConfigured: boolean }
export interface ProfitabilitySeriesRow { date: string; revenue: number; grossProfit: number; grossMargin: number | null; expenseAmount: number | null; netProfit: number | null; profitability: number | null; expensesConfigured: boolean }
export interface ProfitabilityRow extends ProfitabilitySummary { productId: string; cabinetId: string; cabinetName: string; groupId: string | null; groupName: string | null; sellerSku: string | null; wbSku: string | null; productName: string; expensePct: number | null; totalCount: number }
export interface ProfitabilityExpense { cabinetId: string; cabinetName: string; month: string; expensePct: number }
export type ProfitabilitySort = 'revenue' | 'gross_profit' | 'gross_margin' | 'net_profit' | 'profitability';

const ISO = /^\d{4}-\d{2}-\d{2}$/u; const SORTS = new Set<ProfitabilitySort>(['revenue', 'gross_profit', 'gross_margin', 'net_profit', 'profitability']);
function record(value: unknown, context: string): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${context}: сервер вернул неожиданный ответ`); return value as Record<string, unknown>; }
function text(value: unknown, field: string, nullable = false) { if (value == null && nullable) return null; if (typeof value !== 'string' || (!nullable && !value.trim())) throw new Error(`V5 «Рентабельность»: некорректное поле ${field}`); return value; }
function date(value: unknown, field: string, nullable = false) { const result = text(value, field, nullable); if (result === null) return null; if (!ISO.test(result)) throw new Error(`V5 «Рентабельность»: некорректная дата ${field}`); return result; }
function number(value: unknown, field: string, nullable = false) { if (value == null && nullable) return null; const result = typeof value === 'number' ? value : Number(value); if (!Number.isFinite(result)) throw new Error(`V5 «Рентабельность»: некорректное число ${field}`); return result; }
function count(value: unknown, field: string) { const result = number(value, field) as number; if (!Number.isSafeInteger(result) || result < 0) throw new Error(`V5 «Рентабельность»: некорректный счётчик ${field}`); return result; }
function boolean(value: unknown, field: string) { if (typeof value !== 'boolean') throw new Error(`V5 «Рентабельность»: некорректный флаг ${field}`); return value; }
function dimensions(value: unknown, field: string): ProfitabilityDimension[] { if (!Array.isArray(value)) throw new Error(`V5 «Рентабельность»: ${field} должен быть списком`); return value.map((item, index) => { const row = record(item, `${field}[${index}]`); return { id: text(row.id, 'id') as string, name: text(row.name, 'name') as string }; }); }

export function assertProfitabilityFilters(filters: ProfitabilityFilters) { if (!ISO.test(filters.start) || !ISO.test(filters.end) || filters.end < filters.start) throw new Error('V5 «Рентабельность»: некорректный период'); const days = (Date.parse(`${filters.end}T00:00:00Z`) - Date.parse(`${filters.start}T00:00:00Z`)) / 86_400_000; if (days > 731) throw new Error('V5 «Рентабельность»: период не должен превышать 731 день'); if ((filters.cabinetIds?.length || 0) > 100 || (filters.categoryIds?.length || 0) > 100 || (filters.brandIds?.length || 0) > 100 || (filters.productIds?.length || 0) > 500 || (filters.groupIds?.length || 0) > 500) throw new Error('V5 «Рентабельность»: слишком много значений фильтра'); if ((filters.search?.length || 0) > 100) throw new Error('V5 «Рентабельность»: поиск длиннее 100 символов'); return filters; }
export function assertProfitabilitySort(value: string): ProfitabilitySort { if (!SORTS.has(value as ProfitabilitySort)) throw new Error('V5 «Рентабельность»: неизвестная сортировка'); return value as ProfitabilitySort; }
export function parseProfitabilityBounds(value: unknown): ProfitabilityBounds { const row = record(value, 'Границы рентабельности'); return { minDate: date(row.min_date, 'min_date', true), maxDate: date(row.max_date, 'max_date', true) }; }
export function parseProfitabilityFilterOptions(value: unknown): ProfitabilityFilterOptions { const row = record(value, 'Фильтры рентабельности'); return { cabinets: dimensions(row.cabinets, 'cabinets'), categories: dimensions(row.categories, 'categories'), brands: dimensions(row.brands, 'brands'), groups: dimensions(row.groups, 'groups') }; }
function summary(row: Record<string, unknown>): ProfitabilitySummary { return { quantity: number(row.quantity, 'quantity') as number, revenue: number(row.revenue, 'revenue') as number, directCosts: number(row.direct_costs, 'direct_costs') as number, grossProfit: number(row.gross_profit, 'gross_profit') as number, grossMargin: number(row.gross_margin, 'gross_margin', true), expenseAmount: number(row.expense_amount, 'expense_amount', true), netProfit: number(row.net_profit, 'net_profit', true), profitability: number(row.profitability, 'profitability', true), productCount: count(row.product_count, 'product_count'), expensesConfigured: boolean(row.expenses_configured, 'expenses_configured') }; }
export function parseProfitabilitySummary(value: unknown): ProfitabilitySummary { if (!Array.isArray(value) || value.length !== 1) throw new Error('V5 «Рентабельность»: сводка должна содержать одну строку'); return summary(record(value[0], 'Сводка рентабельности')); }
export function parseProfitabilitySeries(value: unknown): ProfitabilitySeriesRow[] { if (!Array.isArray(value)) throw new Error('V5 «Рентабельность»: динамика должна быть списком'); let previous = ''; return value.map((item, index) => { const row = record(item, `Динамика[${index}]`); const current = date(row.period_date, 'period_date') as string; if (current <= previous) throw new Error('V5 «Рентабельность»: даты динамики не упорядочены'); previous = current; return { date: current, revenue: number(row.revenue, 'revenue') as number, grossProfit: number(row.gross_profit, 'gross_profit') as number, grossMargin: number(row.gross_margin, 'gross_margin', true), expenseAmount: number(row.expense_amount, 'expense_amount', true), netProfit: number(row.net_profit, 'net_profit', true), profitability: number(row.profitability, 'profitability', true), expensesConfigured: boolean(row.expenses_configured, 'expenses_configured') }; }); }
export function parseProfitabilityRows(value: unknown): ProfitabilityRow[] { if (!Array.isArray(value)) throw new Error('V5 «Рентабельность»: строки должны быть списком'); let total: number | null = null; return value.map((item, index) => { const row = record(item, `Строки[${index}]`); const rowTotal = count(row.total_count, 'total_count'); if (total === null) total = rowTotal; if (total !== rowTotal) throw new Error('V5 «Рентабельность»: несогласованный total_count'); return { ...summary({ ...row, product_count: 1 }), productId: text(row.product_id, 'product_id') as string, cabinetId: text(row.cabinet_id, 'cabinet_id') as string, cabinetName: text(row.cabinet_name, 'cabinet_name') as string, groupId: text(row.group_id, 'group_id', true), groupName: text(row.group_name, 'group_name', true), sellerSku: text(row.seller_sku, 'seller_sku', true), wbSku: text(row.wb_sku, 'wb_sku', true), productName: text(row.product_name, 'product_name') as string, expensePct: number(row.expense_pct, 'expense_pct', true), totalCount: rowTotal }; }); }
export function parseProfitabilityExpenses(value: unknown): ProfitabilityExpense[] { if (!Array.isArray(value)) throw new Error('V5 «Рентабельность»: расходы должны быть списком'); return value.map((item, index) => { const row = record(item, `Расходы[${index}]`); return { cabinetId: text(row.cabinet_id, 'cabinet_id') as string, cabinetName: text(row.cabinet_name, 'cabinet_name') as string, month: date(row.month, 'month') as string, expensePct: number(row.expense_pct, 'expense_pct') as number }; }); }
