-- Isolated Client Experience storage. Existing analytics data remains local.
insert into storage.buckets (id, name, public)
values ('cx-review-imports', 'cx-review-imports', false)
on conflict (id) do update set public = false;

create table if not exists public.review_import_batches (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'wb_reviews',
  file_name text not null,
  file_hash text not null,
  file_size bigint not null default 0,
  storage_path text not null,
  imported_by uuid not null default auth.uid(),
  imported_at timestamptz not null default now(),
  status text not null default 'processing' check (status in (
    'processing', 'verifying', 'completed', 'cleanup_failed', 'verification_failed', 'failed'
  )),
  total_rows integer not null default 0,
  text_rows integer not null default 0,
  empty_rows integer not null default 0,
  duplicate_rows integer not null default 0,
  rejected_rows integer not null default 0,
  unmatched_product_rows integer not null default 0,
  invalid_date_rows integer not null default 0,
  invalid_rating_rows integer not null default 0,
  inserted_reviews integer not null default 0,
  inserted_empty_rows integer not null default 0,
  inserted_registry_rows integer not null default 0,
  mapping_config jsonb not null default '{}'::jsonb,
  parser_version text not null default 'reviews-v1',
  error_message text,
  verified_at timestamptz,
  file_deleted_at timestamptz
);

create table if not exists public.review_row_registry (
  id bigint generated by default as identity primary key,
  import_batch_id uuid not null references public.review_import_batches(id) on delete restrict,
  source text not null default 'wb_reviews',
  cabinet_name text not null,
  source_review_id text not null,
  has_text boolean not null,
  created_at timestamptz not null default now(),
  unique (source, cabinet_name, source_review_id)
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'wb_reviews',
  import_batch_id uuid not null references public.review_import_batches(id) on delete restrict,
  source_review_id text not null,
  review_date date not null,
  local_product_id text,
  cabinet_name text not null,
  seller_sku text,
  wb_sku text,
  product_name text,
  product_category text,
  product_group_names jsonb not null default '[]'::jsonb,
  reported_brand text,
  rating smallint not null check (rating between 1 and 5),
  review_text text,
  advantages text,
  disadvantages text,
  normalized_text text not null,
  text_hash text not null,
  author_name text,
  country_code text,
  color text,
  size text,
  helpful_down integer not null default 0,
  helpful_up integer not null default 0,
  barcode text,
  seller_response text,
  initial_review_id text,
  additional_review_id text,
  product_match_status text not null default 'unmatched' check (product_match_status in ('matched', 'unmatched')),
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (source, cabinet_name, source_review_id)
);

create table if not exists public.review_fragments (
  id bigint generated by default as identity primary key,
  review_id uuid not null references public.reviews(id) on delete cascade,
  fragment_type text not null check (fragment_type in ('text', 'advantage', 'disadvantage')),
  fragment_text text not null,
  normalized_text text not null,
  created_at timestamptz not null default now(),
  unique (review_id, fragment_type)
);

create table if not exists public.empty_review_stats (
  id bigint generated by default as identity primary key,
  import_batch_id uuid not null references public.review_import_batches(id) on delete restrict,
  source text not null default 'wb_reviews',
  review_date date not null,
  local_product_id text,
  cabinet_name text not null,
  seller_sku text,
  wb_sku text,
  rating smallint not null check (rating between 1 and 5),
  review_count integer not null check (review_count > 0),
  created_at timestamptz not null default now(),
  unique (import_batch_id, review_date, cabinet_name, seller_sku, wb_sku, rating)
);

create index if not exists reviews_date_idx on public.reviews (review_date);
create index if not exists reviews_product_idx on public.reviews (local_product_id, review_date);
create index if not exists reviews_cabinet_idx on public.reviews (cabinet_name, review_date);
create index if not exists reviews_rating_idx on public.reviews (rating, review_date);
create index if not exists reviews_batch_idx on public.reviews (import_batch_id);
create index if not exists review_row_registry_batch_idx on public.review_row_registry (import_batch_id);
create index if not exists review_fragments_review_idx on public.review_fragments (review_id);
create index if not exists empty_review_stats_batch_idx on public.empty_review_stats (import_batch_id);

alter table public.review_import_batches enable row level security;
alter table public.review_row_registry enable row level security;
alter table public.reviews enable row level security;
alter table public.review_fragments enable row level security;
alter table public.empty_review_stats enable row level security;

drop policy if exists review_import_batches_admin_all on public.review_import_batches;
create policy review_import_batches_admin_all on public.review_import_batches
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists review_row_registry_admin_all on public.review_row_registry;
create policy review_row_registry_admin_all on public.review_row_registry
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists reviews_admin_all on public.reviews;
create policy reviews_admin_all on public.reviews
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists review_fragments_admin_all on public.review_fragments;
create policy review_fragments_admin_all on public.review_fragments
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists empty_review_stats_admin_all on public.empty_review_stats;
create policy empty_review_stats_admin_all on public.empty_review_stats
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists cx_review_imports_admin_select on storage.objects;
create policy cx_review_imports_admin_select on storage.objects
  for select to authenticated using (bucket_id = 'cx-review-imports' and public.is_admin());

drop policy if exists cx_review_imports_admin_insert on storage.objects;
create policy cx_review_imports_admin_insert on storage.objects
  for insert to authenticated with check (bucket_id = 'cx-review-imports' and public.is_admin());

drop policy if exists cx_review_imports_admin_update on storage.objects;
create policy cx_review_imports_admin_update on storage.objects
  for update to authenticated using (bucket_id = 'cx-review-imports' and public.is_admin())
  with check (bucket_id = 'cx-review-imports' and public.is_admin());

drop policy if exists cx_review_imports_admin_delete on storage.objects;
create policy cx_review_imports_admin_delete on storage.objects
  for delete to authenticated using (bucket_id = 'cx-review-imports' and public.is_admin());

create or replace function public.verify_review_import_batch(batch_uuid uuid)
returns table (
  verified boolean,
  total_rows integer,
  accounted_rows integer,
  stored_reviews integer,
  stored_empty_rows integer,
  message text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.review_import_batches%rowtype;
  stored_review_count integer;
  stored_empty_count integer;
  stored_registry_count integer;
  accounted integer;
  ok boolean;
  result_message text;
begin
  if not public.is_admin() then
    raise exception 'admin access required';
  end if;

  select * into target from public.review_import_batches where id = batch_uuid for update;
  if not found then raise exception 'review import batch not found'; end if;

  select count(*)::integer into stored_review_count from public.reviews where import_batch_id = batch_uuid;
  select coalesce(sum(stats.review_count), 0)::integer into stored_empty_count
  from public.empty_review_stats as stats where stats.import_batch_id = batch_uuid;
  select count(*)::integer into stored_registry_count
  from public.review_row_registry where import_batch_id = batch_uuid;

  accounted := target.text_rows + target.empty_rows + target.duplicate_rows + target.rejected_rows;
  ok := accounted = target.total_rows
    and stored_review_count = target.text_rows
    and stored_empty_count = target.empty_rows
    and stored_registry_count = target.text_rows + target.empty_rows;
  result_message := case when ok then 'all rows reconciled' else 'row reconciliation failed' end;

  update public.review_import_batches
  set status = case when ok then 'completed' else 'verification_failed' end,
      inserted_reviews = stored_review_count,
      inserted_empty_rows = stored_empty_count,
      inserted_registry_rows = stored_registry_count,
      verified_at = now(),
      error_message = case when ok then null else result_message end
  where id = batch_uuid;

  return query select ok, target.total_rows, accounted, stored_review_count, stored_empty_count, result_message;
end;
$$;

revoke all on function public.verify_review_import_batch(uuid) from public;
grant execute on function public.verify_review_import_batch(uuid) to authenticated;
