import { useMemo, useState, useSyncExternalStore } from 'react';
import { Cell, Line, LineChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from 'recharts';
import DateRangeFilter from '../../components/DateRangeFilter';
import FilterBar from '../../components/FilterBar';
import { getCabinets, getGroups, getMemberships, getMetrics, getProducts, getVersion, subscribe } from '../../data/store';
import { getFilteredProductIds } from '../../data/productFilters';
import { appendToMap } from '../../data/collectionUtils';

type Grouping = 'product' | 'group' | 'cabinet'; type Volume = 'impressions' | 'clicks' | 'carts' | 'orders' | 'ordered_amount'; type Rate = 'impressionOrderCr' | 'ctr' | 'cartCr' | 'clickOrderCr';
const fmt = (value: number) => new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 1 }).format(value);
const volumes: Record<Volume, string> = { impressions: 'Показы', clicks: 'Переходы', carts: 'Корзины', orders: 'Заказы', ordered_amount: 'Заказано, ₽' };
const rates: Record<Rate, string> = { impressionOrderCr: 'CR показ → заказ', ctr: 'CTR', cartCr: 'CR переход → корзина', clickOrderCr: 'CR переход → заказ' };
const aggregate = (rows: { impressions: number; clicks: number; carts: number; orders: number; ordered_amount: number }[]) => { const impressions = rows.reduce((s, r) => s + r.impressions, 0), clicks = rows.reduce((s, r) => s + r.clicks, 0), carts = rows.reduce((s, r) => s + r.carts, 0), orders = rows.reduce((s, r) => s + r.orders, 0), ordered_amount = rows.reduce((s, r) => s + r.ordered_amount, 0); return { impressions, clicks, carts, orders, ordered_amount, ctr: impressions ? clicks / impressions * 100 : 0, cartCr: clicks ? carts / clicks * 100 : 0, clickOrderCr: clicks ? orders / clicks * 100 : 0, impressionOrderCr: impressions ? orders / impressions * 100 : 0, avgPrice: orders ? ordered_amount / orders : 0 }; };
const percentile = (values: number[], p: number) => { const sorted = values.filter(Number.isFinite).sort((a, b) => a - b); return sorted.length ? sorted[Math.floor((sorted.length - 1) * p)] : 0; };
const parseRanges = (value: string) => value.split(',').map(item => item.trim().match(/^(\d+)\s*-\s*(\d+|∞)$/)).filter(Boolean).map(match => ({ from: Number(match![1]), to: match![2] === '∞' ? Infinity : Number(match![2]) }));

export default function FunnelPage() {
  useSyncExternalStore(subscribe, getVersion);
  const metrics = getMetrics(), products = getProducts(), groups = getGroups(), memberships = getMemberships(), cabinets = getCabinets();
  const dates = useMemo(() => [...new Set(metrics.map(metric => metric.date))].sort(), [metrics]);
  const [start, setStart] = useState(() => dates[0] || ''), [end, setEnd] = useState(() => dates.at(-1) || ''), [cabinet, setCabinet] = useState(''), [category, setCategory] = useState(''), [brand, setBrand] = useState(''), [group, setGroup] = useState(''), [query, setQuery] = useState('');
  const [grouping, setGrouping] = useState<Grouping>('product'), [xMetric, setXMetric] = useState<Volume>('impressions'), [yMetric, setYMetric] = useState<Rate>('impressionOrderCr'), [sizeMetric, setSizeMetric] = useState<Volume>('ordered_amount');
  const [rangesInput, setRangesInput] = useState('0-1000, 1000-2000, 2000-4000, 4000-∞'), [hideAnomalies, setHideAnomalies] = useState(true);
  const productMap = useMemo(() => new Map(products.map(p => [p.id, p])), [products]); const groupByProduct = useMemo(() => new Map(memberships.map(m => [m.product_id, groups.find(g => g.id === m.group_id)])), [memberships, groups]);
  const allowedProductIds = useMemo(() => getFilteredProductIds(products, memberships, { cabinetFilter: cabinet, categoryFilter: category, brandFilter: brand, groupFilter: group, skuFilter: query }), [products, memberships, cabinet, category, brand, group, query]);
  const filtered = useMemo(() => metrics.filter(row => (!start || row.date >= start) && (!end || row.date <= end) && allowedProductIds.has(row.product_id)), [metrics, allowedProductIds, start, end]);
  const totals = useMemo(() => aggregate(filtered), [filtered]);
  const mapData = useMemo(() => { const result = new Map<string, typeof filtered>(); filtered.forEach(row => { const p = productMap.get(row.product_id); const name = grouping === 'cabinet' ? cabinets.find(c => c.id === p?.cabinet_id)?.name || 'Без кабинета' : grouping === 'group' ? groupByProduct.get(row.product_id)?.name || 'Без склейки' : p?.sku || row.product_id; appendToMap(result, name, row); }); return [...result.entries()].map(([name, rows]) => ({ name, ...aggregate(rows) })).filter(row => row.impressions > 0).sort((a, b) => b.orders - a.orders); }, [filtered, grouping, productMap, groupByProduct, cabinets]);
  const mapLimitX = useMemo(() => percentile(mapData.map(row => row[xMetric]), .99), [mapData, xMetric]); const mapLimitY = useMemo(() => percentile(mapData.map(row => row[yMetric]), .99), [mapData, yMetric]);
  const visibleMap = useMemo(() => hideAnomalies ? mapData.filter(row => row[xMetric] <= mapLimitX && row[yMetric] <= mapLimitY) : mapData, [mapData, hideAnomalies, xMetric, yMetric, mapLimitX, mapLimitY]);
  const dynamic = useMemo(() => { const byDate = new Map<string, typeof filtered>(); filtered.forEach(row => appendToMap(byDate, row.date, row)); return [...byDate.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([date, rows]) => ({ date: date.slice(5), ...aggregate(rows) })); }, [filtered]);
  const segments = useMemo(() => parseRanges(rangesInput).map(range => { const rows = mapData.filter(row => row.avgPrice >= range.from && row.avgPrice < range.to); const top = [...rows].sort((a, b) => b.impressionOrderCr - a.impressionOrderCr).slice(0, Math.max(1, Math.ceil(rows.length * .25))); return { label: `${fmt(range.from)}–${range.to === Infinity ? '∞' : fmt(range.to)} ₽`, products: rows.length, orders: aggregate(rows).orders, avgCr: aggregate(rows).impressionOrderCr, topCr: aggregate(top).impressionOrderCr }; }), [mapData, rangesInput]);
  if (!metrics.length) return <section className="funnel-page analytics-empty-page">
    <header className="entry-header"><span className="geo-eyebrow">АНАЛИТИКА</span><h1>Воронка продаж</h1><p>Эффективность ассортимента, склеек и ценовых сегментов по данным основной воронки.</p></header>
    <article className="analytics-empty-card"><span>ДАННЫЕ НЕ ЗАГРУЖЕНЫ</span><h2>Воронка пока недоступна</h2><p>Загрузите отчёт «Воронка WB», чтобы увидеть динамику, конверсии и сравнение товарных сегментов.</p></article>
  </section>;
  return <section className="funnel-page"><header className="entry-header"><span className="geo-eyebrow">АНАЛИТИКА</span><h1>Воронка продаж</h1><p>Эффективность ассортимента, склеек и ценовых сегментов по данным основной воронки.</p></header>
    <div className="entry-toolbar table-toolbar entry-analytics-toolbar page-card"><div className="date-filters"><DateRangeFilter label="Период" value={{ start, end }} onChange={period => { setStart(period.start); setEnd(period.end); }} maxDate={dates.at(-1) || end} /></div><FilterBar cabinetFilter={cabinet} categoryFilter={category} brandFilter={brand} groupFilter={group} skuFilter={query} onCabinetChange={setCabinet} onCategoryChange={setCategory} onBrandChange={setBrand} onGroupChange={setGroup} onSkuChange={setQuery} variant="dashboard" /></div>
    <div className="entry-kpis"><article><span>Показы</span><strong>{fmt(totals.impressions)}</strong><small>CTR {fmt(totals.ctr)}%</small></article><article><span>Переходы</span><strong>{fmt(totals.clicks)}</strong><small>Корзины {fmt(totals.carts)}</small></article><article><span>Заказы</span><strong>{fmt(totals.orders)}</strong><small>CR показ → заказ {fmt(totals.impressionOrderCr)}%</small></article><article><span>Заказано</span><strong>{fmt(totals.ordered_amount)} ₽</strong><small>Средняя цена {fmt(totals.avgPrice)} ₽</small></article></div>
    <article className="entry-card"><div className="entry-card-head"><div><h2>Карта эффективности</h2><p>X — {volumes[xMetric].toLowerCase()}, Y — {rates[yMetric].toLowerCase()}, размер — {volumes[sizeMetric].toLowerCase()}.</p></div><div className="entry-map-controls"><select value={grouping} onChange={e => setGrouping(e.target.value as Grouping)}><option value="product">По артикулам</option><option value="group">По склейкам</option><option value="cabinet">По кабинетам</option></select><label>X<select value={xMetric} onChange={e => setXMetric(e.target.value as Volume)}>{Object.entries(volumes).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label><label>Y<select value={yMetric} onChange={e => setYMetric(e.target.value as Rate)}>{Object.entries(rates).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label><label>Размер<select value={sizeMetric} onChange={e => setSizeMetric(e.target.value as Volume)}>{Object.entries(volumes).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label></div></div><label className="anomaly-control"><input type="checkbox" checked={hideAnomalies} onChange={e => setHideAnomalies(e.target.checked)} /> Исключать аномалии (верхний 1% по осям) · скрыто {mapData.length - visibleMap.length}</label><ResponsiveContainer width="100%" height={380}><ScatterChart><XAxis dataKey={xMetric} type="number" domain={[0, mapLimitX || 'auto']}/><YAxis dataKey={yMetric} type="number" unit="%" domain={[0, mapLimitY || 'auto']}/><ZAxis dataKey={sizeMetric} range={[60, 1500]}/><Tooltip content={({ active, payload }) => { const item = payload?.[0]?.payload; return active && item ? <div className="entry-tooltip"><strong>{item.name}</strong><span>{volumes[xMetric]}: {fmt(item[xMetric])}</span><span>{rates[yMetric]}: {fmt(item[yMetric])}%</span><span>{volumes[sizeMetric]}: {fmt(item[sizeMetric])}</span></div> : null; }}/><Scatter data={visibleMap}>{visibleMap.map((item, index) => <Cell key={item.name} fill={['#2563eb','#10b981','#e0a91f','#8b5cf6'][index % 4]}/>)}</Scatter></ScatterChart></ResponsiveContainer></article>
    <div className="entry-bottom"><article className="entry-card"><h2>Динамика</h2><ResponsiveContainer width="100%" height={260}><LineChart data={dynamic}><XAxis dataKey="date"/><YAxis/><Tooltip/><Line dataKey={xMetric} stroke="#e0b329" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></article><article className="entry-card"><h2>Ценовые сегменты</h2><label className="range-input">Диапазоны, ₽<input value={rangesInput} onChange={e => setRangesInput(e.target.value)} placeholder="0-1000, 1000-2000, 2000-∞" /></label><p className="segment-note">Топ-25% — верхняя четверть строк сегмента по CR показ → заказ, а не по количеству заказов.</p><div className="segment-grid">{segments.map(s => <div key={s.label}><strong>{s.label}</strong><span>{fmt(s.avgCr)}% средняя CR</span><span>{fmt(s.topCr)}% топ-25% конверсий</span><small>{s.products} строк · {fmt(s.orders)} заказов</small></div>)}</div></article></div>
    <article className="entry-card entry-table-card"><h2>Артикулы и склейки</h2><div className="entry-table-wrap"><table><thead><tr><th>Сущность</th><th>Показы</th><th>Переходы</th><th>CTR</th><th>Корзины</th><th>Заказы</th><th>CR показ → заказ</th><th>Заказано, ₽</th></tr></thead><tbody>{mapData.map(row => <tr key={row.name}><td>{row.name}</td><td>{fmt(row.impressions)}</td><td>{fmt(row.clicks)}</td><td>{fmt(row.ctr)}%</td><td>{fmt(row.carts)}</td><td>{fmt(row.orders)}</td><td>{fmt(row.impressionOrderCr)}%</td><td>{fmt(row.ordered_amount)}</td></tr>)}</tbody></table></div></article></section>;
}
