import { useEffect, useMemo, useState } from 'react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import DateRangeFilter from '../../components/DateRangeFilter';
import { AnalyticsPageHeader, AnalyticsPanel, AnalyticsToolbar, EmptyState, KpiTile, PanelHeader } from '../../components/AnalyticsPrimitives';
import { loadProfitabilityBounds, loadProfitabilityExpenses, loadProfitabilityFilterOptions, loadProfitabilityRows, loadProfitabilitySeries, loadProfitabilitySummary, setProfitabilityExpense } from '../../features/profitability/profitabilityData';
import type { ProfitabilityExpense, ProfitabilityFilterOptions, ProfitabilityFilters, ProfitabilityRow, ProfitabilitySeriesRow, ProfitabilitySort, ProfitabilitySummary } from '../../features/profitability/profitabilityDataCore';

const EMPTY_SUMMARY: ProfitabilitySummary = { quantity: 0, revenue: 0, directCosts: 0, grossProfit: 0, grossMargin: null, expenseAmount: null, netProfit: null, profitability: null, productCount: 0, expensesConfigured: false };
const EMPTY_OPTIONS: ProfitabilityFilterOptions = { cabinets: [], categories: [], brands: [], groups: [] };
const nf = new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 1 });
const money = (value: number | null) => value === null ? '—' : `${nf.format(value)} ₽`;
const percent = (value: number | null) => value === null ? '—' : `${nf.format(value)}%`;
const ids = (value: string) => value ? [value] : null;
function shiftDate(value: string, days: number) { const date = new Date(`${value}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }

export default function ProfitabilityServerPage() {
  const today = useMemo(() => new Date().toISOString().slice(0, 10), []);
  const [period, setPeriod] = useState({ start: shiftDate(today, -731), end: today }); const [bounds, setBounds] = useState({ minDate: '', maxDate: '' });
  const [options, setOptions] = useState(EMPTY_OPTIONS); const [summary, setSummary] = useState(EMPTY_SUMMARY); const [series, setSeries] = useState<ProfitabilitySeriesRow[]>([]); const [rows, setRows] = useState<ProfitabilityRow[]>([]); const [expenses, setExpenses] = useState<ProfitabilityExpense[]>([]);
  const [cabinet, setCabinet] = useState(''); const [category, setCategory] = useState(''); const [brand, setBrand] = useState(''); const [group, setGroup] = useState(''); const [search, setSearch] = useState(''); const [appliedSearch, setAppliedSearch] = useState('');
  const [sort, setSort] = useState<ProfitabilitySort>('revenue'); const [page, setPage] = useState(0); const [ready, setReady] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [request, setRequest] = useState(0); const [savingExpense, setSavingExpense] = useState('');
  const pageSize = 50;

  useEffect(() => { let active = true; queueMicrotask(() => { if (active) { setLoading(true); setError(''); } }); loadProfitabilityBounds().then(value => { if (!active) return; if (value.minDate && value.maxDate) { setBounds({ minDate: value.minDate, maxDate: value.maxDate }); setPeriod({ start: value.minDate, end: value.maxDate }); } setReady(true); }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : 'Не удалось определить период'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [request]);
  useEffect(() => { if (!ready) return; let active = true; const filters: ProfitabilityFilters = { start: period.start, end: period.end, cabinetIds: ids(cabinet), categoryIds: ids(category), brandIds: ids(brand), groupIds: ids(group), search: appliedSearch || null }; queueMicrotask(() => { if (active) { setLoading(true); setError(''); } }); Promise.all([loadProfitabilityFilterOptions(filters), loadProfitabilitySummary(filters), loadProfitabilitySeries(filters), loadProfitabilityRows(filters, sort, page * pageSize, pageSize), loadProfitabilityExpenses(period.start, period.end)]).then(([nextOptions, nextSummary, nextSeries, nextRows, nextExpenses]) => { if (!active) return; setOptions(nextOptions); setSummary(nextSummary); setSeries(nextSeries); setRows(nextRows); setExpenses(nextExpenses); }).catch(reason => { if (!active) return; setSummary(EMPTY_SUMMARY); setSeries([]); setRows([]); setExpenses([]); setError(reason instanceof Error ? reason.message : 'Не удалось загрузить серверную рентабельность'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [appliedSearch, brand, cabinet, category, group, page, period.end, period.start, ready, request, sort]);
  const totalCount = rows[0]?.totalCount || 0; const pageCount = Math.max(1, Math.ceil(totalCount / pageSize));
  const months = useMemo(() => { const values: string[] = []; const current = new Date(`${period.start.slice(0, 7)}-01T00:00:00Z`); const end = `${period.end.slice(0, 7)}-01`; while (current.toISOString().slice(0, 10) <= end && values.length < 24) { values.push(current.toISOString().slice(0, 10)); current.setUTCMonth(current.getUTCMonth() + 1); } return values; }, [period]);
  const expenseMap = useMemo(() => new Map(expenses.map(item => [`${item.cabinetId}:${item.month}`, item.expensePct])), [expenses]);
  const saveExpense = async (cabinetId: string, month: string, value: string) => { const key = `${cabinetId}:${month}`; setSavingExpense(key); setError(''); try { await setProfitabilityExpense(cabinetId, month, Number(value)); setRequest(current => current + 1); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить расходы'); } finally { setSavingExpense(''); } };

  return <section className="ds-page profit-page profit-page-v2">
    <AnalyticsPageHeader eyebrow="Бизнес-метрики" title="Рентабельность" description="Серверная выручка, прямые расходы и валовая прибыль. Чистая прибыль появляется только после настройки постоянных расходов." meta={<span>V5 · Supabase{bounds.maxDate ? ` · данные по ${bounds.maxDate}` : ''}</span>} />
    <AnalyticsToolbar className="profit-toolbar" status={<span>{summary.expensesConfigured ? 'Постоянные расходы настроены для всего выбранного среза' : 'Чистая прибыль скрыта: заполните постоянные расходы для каждого кабинета и месяца'}</span>} trailing={<button className="ds-button" type="button" onClick={() => { setCabinet(''); setCategory(''); setBrand(''); setGroup(''); setSearch(''); setAppliedSearch(''); setSort('revenue'); setPage(0); if (bounds.minDate) setPeriod({ start: bounds.minDate, end: bounds.maxDate }); }}>Сбросить</button>}>
      <DateRangeFilter label="Период" value={period} onChange={value => { setPeriod(value); setPage(0); }} maxDate={bounds.maxDate || today} />
      {[['Кабинет', cabinet, setCabinet, options.cabinets], ['Категория', category, setCategory, options.categories], ['Бренд', brand, setBrand, options.brands], ['Склейка', group, setGroup, options.groups]].map(([label, value, setter, items]) => <select key={String(label)} aria-label={String(label)} value={String(value)} onChange={event => { (setter as (value: string) => void)(event.target.value); setPage(0); }}><option value="">Все: {String(label).toLocaleLowerCase('ru-RU')}</option>{(items as ProfitabilityFilterOptions['cabinets']).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>)}
      <form className="entry-server-search" onSubmit={event => { event.preventDefault(); setAppliedSearch(search.trim()); setPage(0); }}><input aria-label="Поиск товара" value={search} onChange={event => setSearch(event.target.value)} placeholder="SKU или товар" /><button className="ds-button" type="submit">Найти</button></form>
    </AnalyticsToolbar>
    {error && <EmptyState title="Ошибка V5 «Рентабельность»" description={error} action={<button className="ds-button" type="button" onClick={() => setRequest(value => value + 1)}>Повторить</button>} />}
    {!error && loading ? <EmptyState title="Загрузка рентабельности V5" description="Получаем ограниченные серверные агрегаты и строки." /> : !error && !summary.productCount ? <EmptyState title="Нет опубликованной рентабельности" description="Импортируйте отчёт «Рентабельность» в V5 или измените фильтры." /> : !error && <>
      <section className="ds-kpi-grid profit-kpis"><KpiTile label="Выручка" value={money(summary.revenue)} /><KpiTile label="Прямые расходы" value={money(summary.directCosts)} /><KpiTile label="Валовая прибыль" value={money(summary.grossProfit)} details={`Маржа ${percent(summary.grossMargin)}`} /><KpiTile label="Чистая прибыль" value={money(summary.netProfit)} details={`Рентабельность ${percent(summary.profitability)}`} /></section>
      {!summary.expensesConfigured && <AnalyticsPanel><PanelHeader eyebrow="Параметры расчёта" title="Постоянные расходы по месяцам" description="Сохранение доступно администратору; пустое значение намеренно не считается нулём." /><div className="profit-setting-values">{options.cabinets.flatMap(item => months.map(month => <label key={`${item.id}:${month}`}><span>{item.name} · {month.slice(0, 7)}</span><b><input aria-label={`${item.name} ${month.slice(0, 7)}`} type="number" min="0" max="100" step="0.1" defaultValue={expenseMap.get(`${item.id}:${month}`) ?? ''} disabled={savingExpense === `${item.id}:${month}`} onBlur={event => { if (event.target.value !== '') void saveExpense(item.id, month, event.target.value); }} placeholder="—" />%</b></label>))}</div></AnalyticsPanel>}
      <section className="profit-chart-grid"><AnalyticsPanel className="profit-panel"><PanelHeader eyebrow="Динамика" title="Валовая и чистая прибыль" description="Чистая прибыль имеет пропуски, пока месяц не настроен" /><ResponsiveContainer width="100%" height={290}><LineChart data={series}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" tickFormatter={value => String(value).slice(5)} minTickGap={24} /><YAxis tickFormatter={value => `${Math.round(Number(value) / 1000)}к`} /><Tooltip formatter={value => money(value == null ? null : Number(value))} /><Line dataKey="grossProfit" name="Валовая прибыль" stroke="#8B5CF6" dot={false} /><Line dataKey="netProfit" name="Чистая прибыль" stroke="#10A778" dot={false} connectNulls={false} /></LineChart></ResponsiveContainer></AnalyticsPanel></section>
      <AnalyticsPanel density="data" className="profit-table-panel"><PanelHeader eyebrow="Детализация" title="Товары и датированные склейки" description={`${totalCount} строк · серверная сортировка`} controls={<select aria-label="Сортировка" value={sort} onChange={event => { setSort(event.target.value as ProfitabilitySort); setPage(0); }}><option value="revenue">Выручка</option><option value="gross_profit">Валовая прибыль</option><option value="gross_margin">Маржа</option><option value="net_profit">Чистая прибыль</option><option value="profitability">Рентабельность</option></select>} /><div className="profit-table-wrap"><table className="profit-table profit-table-v2"><thead><tr><th>Артикул / товар</th><th>Кабинет / склейка</th><th>Выручка</th><th>Прямые расходы</th><th>Валовая прибыль</th><th>Маржа</th><th>Пост. расходы, %</th><th>Пост. расходы</th><th>Чистая прибыль</th><th>Рентабельность</th></tr></thead><tbody>{rows.map(row => <tr key={`${row.productId}:${row.groupId || ''}`}><td><strong>{row.sellerSku || row.wbSku || row.productId}</strong><small>{row.productName}</small></td><td>{row.cabinetName}<small>{row.groupName || 'Без склейки'}</small></td><td>{money(row.revenue)}</td><td>{money(row.directCosts)}</td><td>{money(row.grossProfit)}</td><td>{percent(row.grossMargin)}</td><td>{percent(row.expensePct)}</td><td>{money(row.expenseAmount)}</td><td>{money(row.netProfit)}</td><td>{percent(row.profitability)}</td></tr>)}</tbody></table></div><footer className="funnel-table-footer"><span>Страница {page + 1} из {pageCount}</span><div><button type="button" disabled={page === 0} onClick={() => setPage(value => Math.max(0, value - 1))}>←</button><button type="button" disabled={page + 1 >= pageCount} onClick={() => setPage(value => value + 1)}>→</button></div></footer></AnalyticsPanel>
    </>}
  </section>;
}
